### ISSUE TITLE
reduce vertical size of header on download page

### ISSUE THREAD

**Issue by behindtext** [decred/dcrweb#172] opened 2017-11-07 20:04 UTC
the header on the download page takes up a lot of vertical space. further, it has a strange js background animation that doesn't look particularly good, imo.

i suggest making this header smaller.

**Comment by linnutee** [comment] 2017-11-09 00:55
All of the subpages follow the same template at the moment: a large header that holds some image or the interactive animations. 

I understand the issue is sort of more subjective and around the animation concept. Changing height won't fix it. Let's better keep the subpage styles intact and will get another animation going that conveys the page core essence better like stakepools and contributors ones do.

**Comment by dajohi** [comment] 2017-12-10 18:52
Is this still an issue or can this be closed?

**Comment by linnutee** [comment] 2017-12-20 13:24
I think it can be closed. Listed down in the work list to re-work the animation.

**Closed** 2018-08-27 12:58 UTC
