### ISSUE TITLE
Youtube JS errors on homepage

### ISSUE THREAD

**Issue by infertux** [decred/dcrweb#226] opened 2018-01-13 19:40 UTC
I'm getting a bunch of JS errors and warnings related to Youtube with Firefox:

![2018-01-13-193854_598x199_scrot](https://user-images.githubusercontent.com/345702/34909463-68a0c3a8-f899-11e7-8284-e599e0ea461c.png)

The video plays fine though.

**Comment by jholdstock** [comment] 2018-07-15 13:57
Hi @infertux, I am not able to reproduce this. Are you still able to?

**Comment by infertux** [comment] 2018-07-15 19:09
@jholdstock The two errors are gone. However the three warnings are still present. The video still plays fine. Feel free to close this issue if you want to.

**Comment by jholdstock** [comment] 2018-07-16 18:39
Yeah I would suggest we close this. The video works for me on all the browsers I have tested. And besides that, these errors are coming from youtube code which is mostly out of our control.

**Closed** 2018-07-17 09:51 UTC
