### ISSUE TITLE
Always show "decentralized CREDIT"

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#66] opened 2017-05-14 16:43 UTC
Hovering over the main decred logo on the homepage shows a sub-text "decentralized CREDIT". It's not obvious that you can mouseover the logo and I only discovered it by chance.

Personally I think it would make a nice addition to the homepage if the sub-text was shown all the time.

It's been mentioned in Slack that people didn't know decred is an abbreviation of decentralized credit, and it was pointed out in the documentation survey that its not mentioned in the docs either (decred/dcrdocs#243).

**Comment by pvtwarren** [comment] 2017-06-29 12:44
Personally, I feel like the subtility of it is quite neat. I think there is a case to be made for it being something to discover rather than something that is thrown in your face. 

I feel like once people finally discover that decred stands for 'decentralized credit' it makes it a little more special. 

Also, if you think about names like Microsoft for example, there's nobody who is really consciously translating that into micro-software. It's not really something that is essential to know. It's more like a fun fact.

**Comment by linnutee** [comment] 2017-08-09 17:04
I would recommend to close this issue. The sub-text was designed to be this way as an interactive easter egg from the start. Landing page needs to be kept as clear and impactful as possible – so from a visual communication perspective, if it was visible all the time, i'd really question whether it adds more bloat than value. 

It's better to try to make an effort to communicate the name components elsewhere I recon.

**Comment by jolan** [comment] 2017-08-09 17:45
If it is working as designed/intended, that is good enough for me.  Closing.

**Closed by jolan** 2017-08-09 17:45 UTC

**Comment by noahpierau** [comment] 2019-03-19 10:10
We should also change to "decentralized CREDITS"
