### ISSUE TITLE
Apple desktop OS format inconsistency

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#117] opened 2017-08-31 11:22 UTC
Apple's desktop OS is mentioned in different formats. It is written as: Mac OS X, Mac OS, or macOS.

It would be best to have one format, for example: MacOS.

**Comment by jolan** [comment] 2017-08-31 12:22
This has been recently fixed but the update was not pulled and made live.  I will make sure this happens.

Duplicate of #114.

**Closed by jolan** 2017-08-31 12:22 UTC
Labels: duplicate

**Comment by jolan** [comment] 2017-08-31 14:56
Update is live if you want to review.
