### ISSUE TITLE
Link recruiting page from the menu

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#747] opened 2019-11-13 20:31 UTC
I think the [recruiting](https://decred.org/recruiting/) page could use a bit more visibility with a link in the 'hamburger' menu.

**Comment by jholdstock** [comment] 2020-03-09 19:28
Relevant to: #842

**Comment by xaur** [comment] 2020-03-12 17:50
I see "Contributing and Becoming a Contractor" link in the Sustainable block after the redesign. Nice wording there. Linking that from the menu would still be an improvement though.

**Comment by johncodesit** [comment] 2021-01-24 21:27
@xaur  @jholdstock  I believe this issue was already fixed, can you please confirm?

**Comment by xaur** [comment] 2021-01-25 03:26
I see [Contributing](https://decred.org/contributors/) link in the hamburger -> Insights and Resources, but it's different from contributing or [recruiting](https://decred.org/recruiting/).

**Comment by xaur** [comment] 2021-01-25 03:28
And to be honest I don't like this hamburger menu at all. I need to perform an action to see core navigation, and then another action to see sublevels. It does not stimulate exploration. The "old school" web design I like is when common links like About, Downloads, News, Contribute are clearly visible on the top.

But that's out of scope of this issue.

**Comment by jholdstock** [comment] 2021-01-25 09:18
Closing this issue because after >12 months, I don't think anything is going to be changed here.

The nav menu links and footer links, and the hidden hamburger style menu, are chosen by design folks (Eeter & co). They deliberately aimed to reduced a massive set of links on the old site down to a smaller, more focused set on the new site. Slowly adding them back in one-by-one is at odds with that choice.

**Closed by jholdstock** 2021-01-25 09:18 UTC
