### ISSUE TITLE
Images of social media links do not show

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#334] opened 2018-09-08 14:49 UTC
On the sub-page https://www.decred.org/community/ the images of some social media links do not show properly (Twitter, Facebook, YouTube). See screenshot below:

![image](https://user-images.githubusercontent.com/16287891/45255438-c19bc180-b386-11e8-934e-667211e4e5ea.png)

**Comment by linnutee** [comment] 2018-09-12 15:47
I'm unable to replicate that. Could be an old cache issue?

**Comment by karamble** [comment] 2018-09-13 12:59
Same here, unable to replicate. Would be nice to get browser and resolution of your screen.

**Comment by noahpierau** [comment] 2018-09-13 13:16
Screen Resolution is 1280x720 and I'm using FireFox 62.0 (64-bit). I reproduced the issue inside an incognito window on FireFox. When using Edge the images show fine, that's strange indeed.

**Comment by rmykolas** [comment] 2018-09-20 13:11
Unable to replicate as well, if this issue still persists, could you show what errors Firefox console is showing, @noahpierau?

**Comment by noahpierau** [comment] 2018-10-04 00:54
Web console shows:

![image](https://user-images.githubusercontent.com/16287891/46447136-912a2600-c780-11e8-98e2-344cfca5eeaf.png)

TypeError: document.getElementById(...) is null[Learn More] main.js:696:4

https://www.decred.org/content/js/main.js:696:4
https://www.decred.org/content/js/jquery.min.js:2:27060
https://www.decred.org/content/js/jquery.min.js:2:27828
https://www.decred.org/content/js/jquery.min.js:2:29619
https://www.decred.org/content/js/jquery.min.js:2:29804

**Comment by dajohi** [comment] 2018-10-16 17:11
@karamble can you upgrade jquery?  The repo currently has v2.2.0

**Comment by jzbz** [comment] 2018-11-19 05:10
Still an issue for the Twitter logo on Firefox (desktop) works fine on Firefox mobile.

![screenshot_2018-11-19 decred - community](https://user-images.githubusercontent.com/4731927/48687411-45480a80-eb8f-11e8-9b19-070f0f89aee2.png)

**Comment by ZeroASIC** [comment] 2018-11-19 17:47
I'm not able to reproduce this error with Firefox 63.0 (64-bit) on Linux.  I don't see any of the errors either.  What version of Firefox are you using?

**Comment by jzbz** [comment] 2018-11-19 18:50
63.0.1 (64-bit) on Linux.

**Comment by dajohi** [comment] 2019-01-24 19:07
@jzbz is this still occurring?

**Comment by jzbz** [comment] 2019-01-24 19:09
No, as of right now looks fine. @noahpierau if you don't still have the issue you can close this.

**Comment by peterzen** [comment] 2019-01-30 10:32
This has been sorted out as part of the Hugo update, the images should display correctly now.  @noahpierau could you check it please?

**Comment by noahpierau** [comment] 2019-02-05 23:18
Twitter, Facebook and YouTube images are still blank here (clean cache).

Updated to FF 65, resolution is still 1280x720.

Also interesting: the WeChat image breaks if I zoom out to 40%

![image](https://user-images.githubusercontent.com/16287891/52310703-97d1df80-29a4-11e9-846e-aa7e984211ad.png)

**Comment by jzbz** [comment] 2019-02-05 23:20
WeChat breaks for me at 67% zoom but no problem lower or higher, everything else is still cool.

**Comment by jholdstock** [comment] 2019-02-20 11:03
I am also seeing the WeChat logo break on various levels of zoom.

Additionally I have noticed that the Matrix logo sometimes switches out for a Riot.im logo, depending on zoom level. 

I cannot reproduce the facebook/twitter/youtube issue.

**Comment by jholdstock** [comment] 2019-02-20 11:19
#570 created for the issues I can reproduce.

**Comment by noahpierau** [comment] 2019-03-25 12:47
Seems to work fine now, closing this issue.

**Closed** 2019-03-25 12:47 UTC
